### ISSUE TITLE
Openssl error while building module with cargo

### ISSUE THREAD

**Issue by blackbart420** [kamek-pf/polybar-forecast#1]
Hello @kamek-pf 
Thank you for your module, it looks great but I can't compile the program

I try to run the "cargo build --release" command in the polybar-forecast directory.

I get this error : 

   Compiling openssl v0.9.24
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `~/.config/polybar/modules/polybar-forecast/target/release/build/openssl-1a53f5853bfeae35/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

Do you have any idea about what is wrong ?

**Comment by kamek-pf** [comment]
Weird, I thought my commit from September would prevent that sort of build issues.
Also, I cannot reproduce, not quite sure what's going on.
I just updated the master branch, all the dependencies are now up to date.

You can `git pull`, `cargo clean` and try to build again.
If that doesn't work what versions of cargo and rustc are you using ? (`cargo --version` and `rustc --version`) ? 

More importantly, what version of openssl do you have on your system ?

**Comment by blackbart420** [comment]
Thanks for your reply :)

cargo 1.32.0
rustc 1.32.0
OpenSSL 1.1.1a

I did git pull and rebuild and now it builds fine thanks !
