### ISSUE TITLE
What do the two numbers mean?

### ISSUE THREAD

**Issue by gvlasov** [kamek-pf/polybar-forecast#3]
I guess the first one is the current temperature. What is the second one - temperature tomorrow? in an hour?

**Comment by kamek-pf** [comment]
Ah yes, I guess that should go in the readme.
First number is the current temperature, second one is a forecast 3 hours from now.

**Comment by gvlasov** [comment]
@kamek-pf Thanks, great module.

**Comment by kamek-pf** [comment]
Fixed the readme, updated everything and cleaned up the code.
