### ISSUE TITLE
OpenWeather Invalid Response

### ISSUE THREAD

**Issue by Matelasse** [kamek-pf/polybar-forecast#4]
Hi. Thanks for developing this. I've built the binary and put my customized config next to it, but I'm getting the following error:

`Forecast unavailable (Invalid response format from OpenWeatherMap)`
 
I haven't debugged yet and I will soon, but has anyone experienced this? I have a Free api key from openweather.

**Comment by kamek-pf** [comment]
I assume there's a mistake in your configuration somewhere. 
This is the error message you get when HTTP requests return unexpected results, but it really is unhelpful when something goes wrong :/

I'll take a look later today, maybe add a test mode with better error messages to make the setup easier.

**Comment by Matelasse** [comment]
@kamek-pf After debugging I found that it was because of configuration file. I decided to remove the config file dependency and inline values in the code itself. Thanks for the great work!

**Comment by kamek-pf** [comment]
@Matelasse I released a [new version](https://github.com/kamek-pf/polybar-forecast/releases) today, it has new configuration options and better error messages. I believe it should fix the issues you previously had with the config file.
