### ISSUE TITLE
Add option to specificy which elements to display

### ISSUE THREAD

**Issue by khughitt** [kamek-pf/polybar-forecast#5]
Greetings! Would it be possible to extend the configuration to allow for some customization of which elements should be displayed in the output?

In particular, there are a couple tweaks I would find useful:

- toggle display of 3-hr forecast
- add option to display _both_ units (e.g. "32F (0C)")

**Comment by kamek-pf** [comment]
Hey!
Those are two simple changes. I don't have much time at the moment, but I'll try to do this sometime this week.

**Comment by kamek-pf** [comment]
@khughitt I haven't forgotten, I have a bigger release on the way so it's gonna take a bit more time u.u

**Comment by kamek-pf** [comment]
@khughitt 
All done, I invite you to take a look at the [release page](https://github.com/kamek-pf/polybar-forecast/releases). With today's release, I introduced a `display` field in the config file that lets you customize the output format.

In your case, it could look like this:
```toml
display = "{{ temp_icon }} {{ temp_celcius }}°C ({{ temp_fahrenheit }}°F)"
```

I believe we can close this issue now, but let me know if I missed something!

**Comment by khughitt** [comment]
@kamek-pf Thanks for taking the time to work on this! I just grabbed the latest release and tested it out and it works perfectly! :+1:
