### ISSUE TITLE
Add support for reading OWM API key from an environmental variable?

### ISSUE THREAD

**Issue by khughitt** [kamek-pf/polybar-forecast#6]
Got one more request for ya... ;)

Would it be possible/difficult to extend the polybar configuration to support reading API keys from environmental variables?

This way the polybar-forecast config could be safely stored in a dots repo, while the API key could be stored in a separate more secure location.

**Comment by kamek-pf** [comment]
Ah yes, that makes sense. I'll add the option when I have a minute, shouldn't take too long!

**Comment by kamek-pf** [comment]
Fixed!
You can now omit the `api_key` field from the config file and instead set the `OWM_API_KEY` env variable.

**Comment by khughitt** [comment]
Awesome! Thanks for the quick fix!
