### ISSUE TITLE
Unmatched Characters in Polybar

### ISSUE THREAD

**Issue by johnhamelink** [kamek-pf/polybar-forecast#7]
Hi there,

I have polybar-forecast working perfectly with my polybar config, but I wanted to point out a font dependency which hasn't been mentioned: you need a font which has a glyph for the following characters:

```
U+E8E5 <Private Use>
U+E8E4 <Private Use>
U+E8E3 <Private Use>
```

Weather Icons doesn't supply these - what should these icons be, and which fonts would you recommend we use for them?

**Comment by kamek-pf** [comment]
Hey,

These characters are provided by Material Icons: 
![image](https://user-images.githubusercontent.com/3883992/73757767-b98cb080-4737-11ea-94cb-3466fc31d7b0.png)


I have this in my configs, I recommend the same font to avoid rendering issues:

```
font-3 = MaterialIcons:size=21;8
```

**Comment by johnhamelink** [comment]
Thanks! That's what I was needing. I see now that this info is in the docs, but I guess I'd missed it before.
