### ISSUE TITLE
Arm Version

### ISSUE THREAD

**Issue by iot-resister** [kamek-pf/polybar-forecast#8]
I'm trying to load this on arch arm.   I'm gonna go with https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/openweathermap-fullfeatured. But I'd prefer an ARM version of this.   Compiling with the toolchain on the pi or qemu seems like way too much work.

**Comment by kamek-pf** [comment]
You can cross compile a statically linked ARM binary using docker.
From the root of this repo:
```sh
docker run --rm -it -v "$(pwd)":/home/rust/src messense/rust-musl-cross:armv7-musleabihf cargo build --release
```

Binary will be located at `target/armv7-unknown-linux-musleabihf/release/polybar-forecast`.

I haven't tested the resulting binary, but it should work.

**Comment by iot-resister** [comment]
thanks!
